name: Rust: Build binary

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-musl
#     - name: Run tests
#       run: cargo test --verbose
